name: tests

on:
  push:         {branches: [master]}
  pull_request: {branches: [master]}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.23', '1.24']
        goarch: ['amd64']

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        env:
          GOARCH: ${{ matrix.goarch }}
        run: go build -buildvcs=false ./...

      - name: Test
        env:
          GOARCH: ${{ matrix.goarch }}
        run: go test -buildvcs=false ./bttest/ -count=1 -timeout 120s -v
